<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="2" name="tests.test_loader.LoaderTests-20161024074845" skipped="0" tests="17" time="0.007">
	<testcase classname="tests.test_loader.LoaderTests" name="test_init__extension" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_init__extension__default" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_init__file_encoding" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_init__file_encoding__default" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_init__to_unicode" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_init__to_unicode__default" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_read" time="0.001"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_read__encoding__argument" time="0.002"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_read__file_encoding__attribute" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_read__to_unicode__attribute" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_unicode__basic__input_str" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_unicode__basic__input_unicode" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_unicode__basic__input_unicode_subclass" time="0.001"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_unicode__encoding_argument" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_unicode__to_unicode__attribute" time="0.000"/>
	<testcase classname="tests.test_loader.LoaderTests" name="test_load_file" time="0.002">
		<failure message="u'Test template file\r\n' != 'Test template file\n'" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\asalgado\Documents\Laureate\pystache\pystache\tests\test_loader.py", line 202, in test_load_file
    self.assertEqual(template, 'Test template file\n')
AssertionError: u'Test template file\r\n' != 'Test template file\n'
]]>		</failure>
	</testcase>
	<testcase classname="tests.test_loader.LoaderTests" name="test_load_name" time="0.001">
		<failure message="u'Test template file\r\n' != 'Test template file\n'" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\asalgado\Documents\Laureate\pystache\pystache\tests\test_loader.py", line 208, in test_load_name
    self.assertEqual(template, 'Test template file\n')
AssertionError: u'Test template file\r\n' != 'Test template file\n'
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
